# Desarrollo web en Entorno Servidor

services:
  #
  # Servicio Web
  web:
    container_name: dwes-web
    image: php:8.4-apache
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
  #
  #Servicio BBDD
  db:
    container_name: dwes-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
    ports:
      - "3306:3306"